name: CI/CD Pipeline - BitSolucion

on:
  push:
    branches: [ "main", "feature/*", "fix/*" ] # Se activa con main y ramas de trabajo
  pull_request:
    branches: [ "main" ] # Se activa cuando abres un Pull Request hacia main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Publicar aplicación
      run: dotnet publish NotebookValidator.Web.csproj -c Release -o ./publish

    - name: Desplegar a IIS
      # ESTA LÍNEA ES EL SEGURO DE VIDA: Solo corre si el cambio es en MAIN
      if: github.ref == 'refs/heads/main' 
      shell: powershell
      run: |
        Import-Module WebAdministration
        $poolName = "bitsolucion" 
        
        Write-Host "--- Iniciando despliegue en PRODUCCIÓN ---"
        Stop-WebAppPool -Name $poolName -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 5
        xcopy .\publish\* C:\inetpub\miapp\publish\ /E /H /C /I /Y
        Start-WebAppPool -Name $poolName -ErrorAction SilentlyContinue
        Write-Host "--- Despliegue completado ---"